---
#################################################
# Update APT Cache
#################################################

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

#################################################
# Install Apache
#################################################

- name: Install Apache
  ansible.builtin.apt:
    name: apache2
    state: present

- name: Ensure Apache service is enabled and running
  ansible.builtin.service:
    name: apache2
    enabled: true
    state: started
