---
#################################################
# Install MySQL
#################################################

- name: Install MySQL Server
  ansible.builtin.apt:
    name: mysql-server
    state: present
    update_cache: true

#################################################
# Enable and Start MySQL
#################################################

- name: Ensure MySQL service is enabled and running
  ansible.builtin.service:
    name: mysql
    enabled: true
    state: started

#################################################
# Install Python MySQL Library
#################################################

- name: Install Python MySQL library
  ansible.builtin.apt:
    name: python3-pymysql
    state: present

#################################################
# Create WordPress Database
#################################################

- name: Create WordPress database
  community.mysql.mysql_db:
    name: "{{ wordpress_database }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

#################################################
# Create WordPress Database User
#################################################

- name: Create WordPress database user
  community.mysql.mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    priv: "{{ wordpress_database }}.*:ALL"
    host: localhost
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
